services:
# ---- Development ----
  frontend-dev:
    restart: unless-stopped
    build:
      context: ../frontend/
      target: development
    container_name: frontend-dev
    ports:
      - "5173:5173"
    volumes:
      - ../frontend/src:/app/src
      - ../frontend/public:/app/public
      - frontend_node_modules:/app/node_modules
    networks:
      - frontend
    profiles: ["dev"]

  backend-dev:
    restart: unless-stopped
    build:
      context: ../backend/
      target: development
    container_name: backend-dev
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ../backend/src:/app/src
      - backend_node_modules:/app/node_modules
    env_file:
      - ../.env
    networks:
      - backend
      - database
    profiles: ["dev"]

# ---- Production ----
  frontend-prod:
    restart: unless-stopped
    build:
      context: ../frontend/
      target: production
    container_name: frontend-prod
    ports:
      - "80:80"
    networks:
      - frontend
    profiles: ["prod"]

  backend-prod:
    restart: unless-stopped
    build:
      context: ../backend/
      target: production
    container_name: backend-prod
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - ../.env
    networks:
      - backend
      - database
    profiles: ["prod"]


volumes:
  frontend_node_modules:
  backend_node_modules:

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
  database:
    driver: bridge
